name: Nix Cache
description: Cache Nix File To Temporary Directory

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo systemctl stop nix-daemon
        sudo cp -r /nix /tmp/nix-cache

        sudo rm -rf /tmp/nix-cache/var/nix/daemon-socket/socket
        sudo rm -rf /tmp/nix-cache/var/nix/userpool
        sudo rm -rf /tmp/nix-cache/var/nix/gc.lock
        sudo rm -rf /tmp/nix-cache/var/nix/db/big-lock
        sudo rm -rf /tmp/nix-cache/var/nix/db/reserved
        sudo rm -rf /tmp/nix-cache/var/nix/userpool2/slot-0

        sudo chown -R 777 /tmp/nix-cache
        ls -a /tmp/nix-cache
